### ISSUE TITLE
STDERR is not written to ascii output file

### ISSUE THREAD

**Issue by nbassler** [DataMedSci/pymchelper#119]
expected a 5th column with the errors included.
`convertmc --many "*bdo" ./results/.`

**Comment by grzanka** [comment]
You haven't specified any converter (which means a default ASCII convert was used).
Default ASCII converter is fully compatible with old bdo2txt converter and doesn't save stderr.

There is however *plotdata* converter, producing nice ASCII files.

I advice to use it together with gnuplot converter, so you will have both:
 - ascii data, readable by gnuplot and gnuplot scripts.

Fixing this issue is not possible without braking bdo2txt compatibility.
Most of the tests check this compatibility.

**Comment by grzanka** [comment]
I'd recomment first a discussion what the default converter should be and if we keep bdo2txt compatibility or not ?

Do we need 2 ASCII converters ?

Right now default converter (bdo2txt like) is always producing 4 columns.
*plotdata* is producing only columns with variable data (i.e. for 1-D plot only 2 columns)

**Comment by nbassler** [comment]
This is too academic, there are hardly any users there which will suffer unrecoverable losses by adding an extra column. In fact it will get closer to what FLUKA outputs.

I see this entirely from user perspective, what would I expect by entering the simple command: `convertmc --many "*bdo" ./results`, and I really need the errorbars.

**Comment by grzanka** [comment]
If you need error bars now, please use *plotdata* converter, it will produce ASCII files with error bars in.

Adding an extra column to default converter will require breaking tests. If the PR is merged as it is now, then all the tests will be broken and further development much harder.

**Comment by nbassler** [comment]
I wont touch this anymore.
