### ISSUE TITLE
output .dos cubes and similar as sparse martices

### ISSUE THREAD

**Issue by nbassler** [DataMedSci/pymchelper#235]
needed by https://github.com/pytrip/optirt
@okejdokej probably knows in what exact format this should be
@pititomy

**Comment by okejdokej** [comment]
Hi, as a starting point I will say that we need at least two arrays, one with indexes and a second one with data. The indexes indicate the position in the matrix, i.e, let say going from the left to the right, up to down and front to back (this is arbitrary, but is good to know when reconstructing the original matrix). 
Then, a two dimensional matrix as this:     2 0 9
                                                                   3 0 0
                                                                   0 5 7
is equivalent to: ind=[0, 2, 3, 7, 8]; data=[2, 9, 3, 5, 7];

**Comment by grzanka** [comment]
scipy offers wide collection of sparse matrices, see https://docs.scipy.org/doc/scipy/reference/sparse.html
which one would suit you the best ?

If you use python we could simply save it in native NPZ format:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.save_npz.html#scipy.sparse.save_npz

This format however is not easily read in other languages.

**Comment by okejdokej** [comment]
It sounds good, the idea was to use python, so sparse.save_npz is ok.
I think the sparse block matrix is the good one, because the matrixes will be locally dense.
The main operations, if any, that will be performed between matrixes will be additions and constant multiplication, in order to evaluate a given constraint or objective value.

**Comment by grzanka** [comment]
Also keep in mind, that scipy sparse matrix is limited to 2D.
If we limit ourselves to treatment planning images where slices are commonly used, then we could use a dictionary where key would be slice number and value a corresponding sparse matrix for a slice.

Saving several sparse matrices into a single file is straight-forward and can be done as described in:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.save_npz.html#scipy.sparse.save_npz

If you plan to use the sparse matrices only for TPS-related data, then I suggest to implement it as a feature of pytrip.

**pymchelper** is assumed to be converter where input comes from Monte-Carlo codes (Fluka , SHIELD-HIT) and can be saved in various formats (including TRiP98 format, .dos).

**pytrip** is assumed to deal with TRiP98 data (i.e. read and write .dos). If the aim of this issue is to have sparse matrices for TRiP98 data mostly, then lets put it there. 

Still if you need to convert to sparse matrices file generated by SH12A, then I'd suggest to convert it to the .dos/.hed and then use pytrip sparse matrix format.

Another question is if you want to add somewhere in the file with sparse matrix information kept in TRiP98 header file, like spacing ?

**Comment by nbassler** [comment]
@grzanka issue is, we will have to generate a lot of data in form of .bdo files. Converting the .bdo files directly to sparse matrices would be appreciated. Also we may have to fallback to FLUKA, so IMHO it would make sense to have it implemented on pymchelper level.

Anyhow... did I just hear you arguing for (re-)introducing a SciPy dependency? :o)

**Comment by grzanka** [comment]
OK, I see the point now. If the use case is to convert mostly .bdo then it can be easily done here.

But keep in mind that pymchelper cannot read TRiP98 data, so you won't be able to convert .dos/.hed directly to sparse format.

As for scipy - I was planning to do it same way as in trip-writer, only on demand.

Right now I have in mind sth like that:

```
import numpy as np

y = np.zeros(shape=(100,120,300))
y[50, 20, 10] = 137
y[1,2, 3] = 128


def save_sps(filename, x):
    indices = np.nonzero(x)
    data = x[indices]
    print("saving indices", indices)
    print("saving data", data)
    print("saving shape", x.shape)
    np.savez(filename, data=data, indices=indices, shape=x.shape)


def load_sps(filename):
    npzfile = np.load(filename)
    return npzfile['data'], npzfile['indices'], npzfile['shape']

def unpack_sps(data, indices, shape):
    result = np.zeros(shape)
    for ind, dat in zip(indices, data):
        result[ind] = dat
    return result

save_sps("data.npz", y)

data, indices, shape = load_sps("data.npz")

print("loading indices", indices)
print("loading data", data)
print("loading shape", shape)

z = unpack_sps(data, indices, shape)

print("y[50, 20, 10] = ", y[50, 20, 10])
```

I can make a PR with that, but first I wanted to discuss if such data format is suitable for you

**Comment by nbassler** [comment]
for me it looks ok, but @okejdokej will have the last word here, because it is her optimizer which should load the data.

**Comment by okejdokej** [comment]
I think it looks ok, as well :-)

**Comment by grzanka** [comment]
OK, so I start preparing PR for that. 
What do you think about following naming:

```
convertmc sparse --many "*.bdo"
```

Do you also want (as an option) to disregards close-to-zero values ?
It could work in the following way:

```
convertmc sparse --many "*.bdo" --threshold=0.00001
```

?

**Comment by okejdokej** [comment]
I think is a good idea.

**Comment by pititomy** [comment]
Putting a threshold is definitely a good idea I think, to reduce file size with minimal data loss.

**Comment by grzanka** [comment]
I also leave to you implementing in efficient way all operations (addition, multiplication) on such form (its COOrdinate format) of sparse matrices.

Multiplication by a const factor is very easy.

Having indices stored in plain numpy array would require some tricks when doing addition, to avoid plain python loops. Union operation exists in numpy, but only for 1D case:
https://docs.scipy.org/doc/numpy/reference/generated/numpy.union1d.html#numpy.union1d
